# Generated by Django 5.1.1 on 2025-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_app', '0002_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='d_profile.jfif', null=True, upload_to='media/'),
        ),
    ]
