# Generated by Django 5.1.1 on 2026-05-17 08:41

import axis_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_app", "0004_add_card_activation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="card_number",
            field=models.CharField(
                default=axis_app.models.generate_card_number, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cvv",
            field=models.CharField(default=axis_app.models.generate_cvv, max_length=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expiry_date",
            field=models.CharField(
                default=axis_app.models.generate_expiry_date, max_length=7
            ),
        ),
    ]
